version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
    ports:
      - '80:80'
    depends_on:
      - aspapp
      - aspapp1
    restart: always

  aspapp:
    build: ./ao-docker-tech-test
    container_name: aspapp
    hostname: aspapp
    ports:
      - '80'
    restart: always

  aspapp1:
    build: ./ao-docker-tech-test1
    container_name: aspapp1
    hostname: aspapp1
    ports:
      - '80'
    restart: always

